import { Injectable } from '@angular/core';
import { ShowService, Show } from './show.service';

@Injectable()
export class SuperstarsService {

  private superstars: any[] = [
    {
      name: "Adam Cole",
      debut: 2008,
      hometown: "Panama City, Florida",
      height: 1.80,
      weight: 95,
      finisher: "The Last Shot",
      show: this._showService.getShow("2"),
      faction: "The Undisputed Era",
      img: "assets/img/superstars/adam_cole.png",
      imgFull: "assets/img/superstars_full/adam_cole.png",
      logo: "assets/img/logo/the_undisputed_era.png",
      music: "zaPnhZtcu8w"
    },
    {
      name: "Bobby Fish",
      debut: 2002,
      hometown: "Saratoga Springs, Nueva York",
      height: 1.80,
      weight: 89,
      finisher: "Sleeping With The Fishes",
      show: this._showService.getShow("2"),
      faction: "The Undisputed Era",
      img: "assets/img/superstars/bobby_fish.png",
      imgFull: "assets/img/superstars_full/bobby_fish.png",
      logo: "assets/img/logo/the_undisputed_era.png",
      music: "zaPnhZtcu8w"
    },
    {
      name: "Kyle O'Reilly",
      debut: 2005,
      hometown: "Vancouver, Columbia Británica",
      height: 1.80,
      weight: 91,
      finisher: "Reverse Capture Suplex",
      show: this._showService.getShow("2"),
      faction: "The Undisputed Era",
      img: "assets/img/superstars/kyle_oreilly.png",
      imgFull: "assets/img/superstars_full/kyle_oreilly.png",
      logo: "assets/img/logo/the_undisputed_era.png",
      music: "zaPnhZtcu8w"
    },
    {
      name: "Roderick Strong",
      debut: 2000,
      hometown: "New Orleans, Louisiana",
      height: 1.78,
      weight: 91,
      finisher: "End of Heartache",
      show: this._showService.getShow("2"),
      faction: "The Undisputed Era",
      img: "assets/img/superstars/roderick_strong.png",
      imgFull: "assets/img/superstars_full/roderick_strong.png",
      logo: "assets/img/logo/the_undisputed_era.png",
      music: "zaPnhZtcu8w"
    },
    {
      name: "Drew McIntyre",
      debut: 2001,
      hometown: "Ayr, Escocia",
      height: 1.96,
      weight: 115,
      finisher: "Claymore Kick",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/drew_mcintyre.png",
      imgFull: "assets/img/superstars_full/drew_mcintyre.png",
      music: "sJuG8TOhb9E"
    },
    {
      name: "Matt Hardy",
      nickname: "Woken",
      debut: 1995,
      hometown: "Cameron, Carolina del Norte",
      height: 1.88,
      weight: 106,
      finisher: "Twist of Fate",
      show: this._showService.getShow("1"),
      faction: "The Hardy Boyz",
      img: "assets/img/superstars/matt_hardy.png",
      imgFull: "assets/img/superstars_full/matt_hardy.png",
      logo: "assets/img/logo/hardy_boyz.png",
      music: "G5exT0Vm93k"
    },
    {
      name: "Jeff Hardy",
      debut: 1993,
      hometown: "Cameron, Carolina del Norte",
      height: 1.88,
      weight: 102,
      finisher: "Swanton Bomb",
      show: this._showService.getShow("1"),
      faction: "The Hardy Boyz",
      img: "assets/img/superstars/jeff_hardy.png",
      imgFull: "assets/img/superstars_full/jeff_hardy.png",
      logo: "assets/img/logo/hardy_boyz.png",
      music: "wRz2YP7_8t0"
    },
    {
      name: "Bray Wyatt",
      debut: 2009,
      hometown: "Brooksville, Florida",
      height: 1.91,
      weight: 129,
      finisher: "Mandible claw / Sister Abigail",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/bray_wyatt.png",
      imgFull: "assets/img/superstars_full/bray_wyatt.png",
      logo: "assets/img/logo/bray_wyatt.jpg",
      music: "c2mgVnFJPHM"
    },
    {
      name: "Kevin Owens",
      debut: 2000,
      hometown: "Marieville, Quebec, Canadá",
      height: 1.83,
      weight: 121,
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/kevin_owens.png",
      imgFull: "assets/img/superstars_full/kevin_owens.png",
      logo: "assets/img/logo/kevin_owens.png",
      music: "90XjKN_M09Y"
    },
    {
      name: "Seth Rollins",
      debut: 2005,
      hometown: "Davenport, Iowa",
      height: 1.87,
      weight: 98,
      finisher: "Curb Stomp",
      show: this._showService.getShow("0"),
      faction: "The Shield",
      img: "assets/img/superstars/seth_rollins.png",
      imgFull: "assets/img/superstars_full/seth_rollins.png",
      logo: "assets/img/logo/seth_rollins.png",
      music: "q0QlvMwLMw0"
    },
    {
      name: "Tommaso Ciampa",
      debut: 2005,
      hometown: "Milwaukee, Wisconsin",
      height: 1.80,
      weight: 91,
      finisher: "Fairy Tale Ending",
      show: this._showService.getShow("2"),
      faction: "#DIY",
      img: "assets/img/superstars/tommaso_ciampa.png",
      imgFull: "assets/img/superstars_full/tommaso_ciampa.png",
      logo: "assets/img/logo/tommaso_ciampa.png",
      music: "ALGdUgNyiYQ"
    },
    {
      name: "Becky Lynch",
      nickname: "The Man",
      debut: 2002,
      hometown: "Dublin, Irlanda",
      height: 1.68,
      weight: 61,
      finisher: "The Disarm-Her",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/becky_lynch.png",
      imgFull: "assets/img/superstars_full/becky_lynch.png",
      logo: "assets/img/logo/becky_lynch.png",
      music: "KUMFOJc0cD8"
    },
    {
      name: "AJ Styles",
      debut: 1998,
      hometown: "Gainesville, Georgia",
      height: 1.80,
      weight: 98,
      finisher: "Styles Clash",
      show: this._showService.getShow("0"),
      faction: "The O.C.",
      img: "assets/img/superstars/aj_styles.png",
      imgFull: "assets/img/superstars_full/aj_styles.png",
      logo: "assets/img/logo/the_oc.png",
      music: "Dxwa-BYP3GA"
    },
    {
      name: "Luke Gallows",
      debut: 2005,
      hometown: "Chicago, Illinois",
      height: 2.03,
      weight: 138,
      finisher: "Magic Killer",
      show: this._showService.getShow("0"),
      faction: "The O.C.",
      img: "assets/img/superstars/luke_gallows.png",
      imgFull: "assets/img/superstars_full/luke_gallows.png",
      logo: "assets/img/logo/the_oc.png",
      music: "-rKvadS8Q_U"
    },
    {
      name: "Karl Anderson",
      debut: 2002,
      hometown: "Pipestone, Minnesota",
      height: 1.83,
      weight: 110,
      finisher: "Magic Killer",
      show: this._showService.getShow("0"),
      faction: "The O.C.",
      img: "assets/img/superstars/karl_anderson.png",
      imgFull: "assets/img/superstars_full/karl_anderson.png",
      logo: "assets/img/logo/the_oc.png",
      music: "-rKvadS8Q_U"
    },
    {
      name: "Shinsuke Nakamura",
      debut: 2002,
      hometown: "Mineyama, Kyoto, Japón",
      height: 1.88,
      weight: 103,
      finisher: "Kinshasa",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/shinsuke_nakamura.png",
      imgFull: "assets/img/superstars_full/shinsuke_nakamura.png",
      logo: "assets/img/logo/shinsuke_nakamura.png",
      music: "7uP5cpdXaHg"
    },
    {
      name: "Brock Lesnar",
      debut: 2000,
      hometown: "Minneapolis, Minnesota",
      height: 1.91,
      weight: 130,
      finisher: "F-5",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/brock_lesnar.png",
      imgFull: "assets/img/superstars_full/brock_lesnar.png",
      logo: "assets/img/logo/brock_lesnar.png",
      music: "6K07yVtzioI"
    },
    {
      name: "Johnny Gargano",
      debut: 2005,
      hometown: "Cleveland, Ohio",
      height: 1.78,
      weight: 90,
      finisher: "Gargano Escape",
      show: this._showService.getShow("2"),
      faction: "#DIY",
      img: "assets/img/superstars/johnny_gargano.png",
      imgFull: "assets/img/superstars_full/johnny_gargano.png",
      logo: "assets/img/logo/johnny_gargano.png",
      music: "A4YEEsZJgjc"
    },
    {
      name: "Randy Orton",
      debut: 2000,
      hometown: "St. Louis, Missouri",
      height: 1.96,
      weight: 113,
      finisher: "RKO",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/randy_orton.png",
      imgFull: "assets/img/superstars_full/randy_orton.png",
      logo: "assets/img/logo/randy_orton.png",
      music: "SqrjON7UgPo"
    },
    {
      name: "Robert Roode",
      debut: 1998,
      hometown: "Toronto, Ontario",
      height: 1.83,
      weight: 107,
      finisher: "Glorious DDT",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/robert_roode.png",
      imgFull: "assets/img/superstars_full/robert_roode.png",
      music: "7n-W-0VMOOw"
    },
    {
      name: "WALTER",
      debut: 2005,
      hometown: "Vienna, Austria",
      height: 1.93,
      weight: 141,
      finisher: "Burning Lariat",
      show: this._showService.getShow("3"),
      faction: "Imperium",
      img: "assets/img/superstars/walter.png",
      imgFull: "assets/img/superstars_full/walter.png",
      music: "XuvSKH-OCY0"
    },
    {
      name: "Pete Dunne",
      debut: 2005,
      hometown: "Birmingham, Inglaterra",
      height: 1.78,
      weight: 93,
      finisher: "Bitter End",
      show: this._showService.getShow("3"),
      img: "assets/img/superstars/pete_dunne.png",
      imgFull: "assets/img/superstars_full/pete_dunne.png",
      logo: "assets/img/logo/pete_dunne.png",
      music: "5dt4KAm2DZc"
    },
    {
      name: "Bayley",
      debut: 2008,
      hometown: "San Jose, California",
      height: 1.63,
      weight: 54,
      finisher: "Bayley to Belly",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/bayley.png",
      imgFull: "assets/img/superstars_full/bayley.png",
      logo: "assets/img/logo/bayley.png",
      music: "5HVA5gifBuA"
    },
    {
      name: "Aleister Black",
      debut: 2002,
      hometown: "Ámsterdam, Holanda",
      height: 1.83,
      weight: 93,
      finisher: "Black Mass",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/aleister_black.png",
      imgFull: "assets/img/superstars_full/aleister_black.png",
      logo: "assets/img/logo/aleister_black.png",
      music: "zlyiDGo3WdI"
    },
    {
      name: "Alexa Bliss",
      debut: 2013,
      hometown: "Columbus, Ohio",
      height: 1.55,
      weight: 46,
      finisher: "Twisted Bliss",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/alexa_bliss.png",
      imgFull: "assets/img/superstars_full/alexa_bliss.png",
      logo: "assets/img/logo/alexa_bliss.png",
      music: "KMZDd7QsiSw"
    },
    {
      name: "Braun Strowman",
      debut: 2013,
      hometown: "Sherrills Ford, Carolina del Norte",
      height: 2.03,
      weight: 175,
      finisher: "Running Powerslam",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/braun_strowman.png",
      imgFull: "assets/img/superstars_full/braun_strowman.png",
      logo: "assets/img/logo/braun_strowman.png",
      music: "o2HsJBuR9Mc"
    },
    {
      name: "Charlotte Flair",
      debut: 2012,
      hometown: "The Queen City",
      height: 1.78,
      weight: 65,
      finisher: "Natural Selection / Figure Eight",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/charlotte_flair.png",
      imgFull: "assets/img/superstars_full/charlotte_flair.png",
      logo: "assets/img/logo/charlotte_flair.png",
      music: "TWz__Scx16I"
    },
    {
      name: "Andrade Almas",
      debut: 2003,
      hometown: "Gómez Palacio, Durango, México",
      height: 1.80,
      weight: 82,
      finisher: "La Sombra",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/andrade.png",
      imgFull: "assets/img/superstars_full/andrade.png",
      music: "CJLiiFMhaxs"
    },
    {
      name: "Roman Reigns",
      debut: 2010,
      hometown: "Pensacola, Florida",
      height: 1.91,
      weight: 130,
      finisher: "Spear",
      show: this._showService.getShow("1"),
      faction: "The Shield",
      img: "assets/img/superstars/roman_reigns.png",
      imgFull: "assets/img/superstars_full/roman_reigns.png",
      logo: "assets/img/logo/roman_reigns.png",
      music: "P2oxEJoRAnc"
    },
    {
      name: "Dusty Rhodes",
      debut: 1967,
      hometown: "Austin, Texas",
      height: 1.85,
      weight: 131,
      finisher: "Bionic Elbow",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/dusty_rhodes.png",
      imgFull: "assets/img/superstars_full/dusty_rhodes.png",
      music: "oNPq7LHZxCA"
    },
    {
      name: "Kassius Ohno",
      debut: 1998,
      hometown: "Dayton, Ohio",
      height: 1.93,
      weight: 123,
      finisher: "KO",
      show: this._showService.getShow("3"),
      img: "assets/img/superstars/kassius_ohno.png",
      imgFull: "assets/img/superstars_full/kassius_ohno.png",
      music: "sYvolLQHVTs"
    },
    {
      name: "Sasha Banks",
      debut: 2010,
      hometown: "Boston, Massachusetts",
      height: 1.65,
      weight: 52,
      finisher: "Bank Statement",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/sasha_banks.png",
      imgFull: "assets/img/superstars_full/sasha_banks.png",
      logo: "assets/img/logo/sasha_banks.png",
      music: "Spw2akAZDl0"
    },
    {
      name: "Finn Bálor",
      debut: 2000,
      hometown: "Bray, Irlanda",
      height: 1.80,
      weight: 82,
      finisher: "Coup de Grâce",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/finn_balor.png",
      imgFull: "assets/img/superstars_full/finn_balor.png",
      logo: "assets/img/logo/finn_balor.png",
      music: "zPaLr1H0wgw"
    },
    {
      name: "Daniel Bryan",
      debut: 1999,
      hometown: "Aberdeen, Washington",
      height: 1.78,
      weight: 95,
      finisher: "\"Yes!\" Lock",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/daniel_bryan.png",
      imgFull: "assets/img/superstars_full/daniel_bryan.png",
      logo: "assets/img/logo/daniel_bryan.jpg",
      music: "FN1eQo-YOwM"
    },
    {
      name: "Shayna Baszler",
      debut: 2015,
      hometown: "Sioux Falls, Dakota del Sur",
      height: 1.70,
      weight: 62,
      finisher: "Ace of Spades",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/shayna_baszler.png",
      imgFull: "assets/img/superstars_full/shayna_baszler.png",
      logo: "assets/img/logo/shayna_baszler.png",
      music: "rCmRrhOe104"
    },
    {
      name: "Erik",
      debut: 2003,
      hometown: "Cleveland, Ohio",
      height: 1.85,
      weight: 109,
      finisher: "The Viking Experience",
      show: this._showService.getShow("0"),
      faction: "The Viking Raiders",
      img: "assets/img/superstars/erik.png",
      imgFull: "assets/img/superstars_full/erik.png",
      music: "4CP3VUMHROI"
    },
    {
      name: "Ivar",
      debut: 2001,
      hometown: "Lynn, Massachusetts",
      height: 1.85,
      weight: 120,
      finisher: "The Viking Experience",
      show: this._showService.getShow("0"),
      faction: "The Viking Raiders",
      img: "assets/img/superstars/ivar.png",
      imgFull: "assets/img/superstars_full/ivar.png",
      music: "4CP3VUMHROI"
    },
    {
      name: "R-Truth",
      debut: 1997,
      hometown: "Charlotte, Carolina del Norte",
      height: 1.85,
      weight: 107,
      finisher: "Whats Up?",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/r_truth.png",
      imgFull: "assets/img/superstars_full/r_truth.png",
      logo: "assets/img/logo/r_truth.png",
      music: "lr6TKVk9XhU"
    },
    {
      name: "Kairi Sane",
      debut: 2012,
      hometown: "Hikari, Yamaguchi, Japón",
      height: 1.55,
      weight: 52,
      finisher: "Insane Elbow / The Anchor",
      show: this._showService.getShow("0"),
      faction: "The Kabuki Warriors",
      img: "assets/img/superstars/kairi_sane.png",
      imgFull: "assets/img/superstars_full/kairi_sane.png",
      music: "NwB2hyv7wwc"
    },
    {
      name: "Asuka",
      debut: 2004,
      hometown: "Osaka, Japón",
      height: 1.60,
      weight: 62,
      finisher: "Asuka Lock",
      show: this._showService.getShow("0"),
      faction: "The Kabuki Warriors",
      img: "assets/img/superstars/asuka.png",
      imgFull: "assets/img/superstars_full/asuka.png",
      music: "7jQSSoBwOJ4"
    },
    {
      name: "Big E",
      debut: 2009,
      hometown: "Tampa, Florida",
      height: 1.80,
      weight: 130,
      finisher: "Big Ending",
      show: this._showService.getShow("1"),
      faction: "The New Day",
      img: "assets/img/superstars/big_e.png",
      imgFull: "assets/img/superstars_full/big_e.png",
      logo: "assets/img/logo/new_day.png",
      music: "43RP-ovFoeE"
    },
    {
      name: "Kofi Kingston",
      debut: 1998,
      hometown: "Tampa, Florida",
      height: 1.85,
      weight: 96,
      finisher: "Trouble in Paradise",
      show: this._showService.getShow("1"),
      faction: "The New Day",
      img: "assets/img/superstars/kofi_kingston.png",
      imgFull: "assets/img/superstars_full/kofi_kingston.png",
      logo: "assets/img/logo/new_day.png",
      music: "43RP-ovFoeE"
    },
    {
      name: "Xavier Woods",
      debut: 2005,
      hometown: "Atlanta",
      height: 1.75,
      weight: 94,
      finisher: "Lost in the Woods",
      show: this._showService.getShow("1"),
      faction: "The New Day",
      img: "assets/img/superstars/xavier_woods.png",
      imgFull: "assets/img/superstars_full/xavier_woods.png",
      logo: "assets/img/logo/new_day.png",
      music: "43RP-ovFoeE"
    },
    {
      name: "Tyler Bate",
      debut: 2012,
      hometown: "Netherton, Dudley, Inglaterra",
      height: 1.70,
      weight: 79,
      finisher: "Tyler Driver '97",
      show: this._showService.getShow("3"),
      faction: "Moustache Mountain",
      img: "assets/img/superstars/tyler_bate.png",
      imgFull: "assets/img/superstars_full/tyler_bate.png",
      logo: "assets/img/logo/moustache_mountain.png",
      music: "dN4GqZLiFDs"
    },
    {
      name: "Velveteen Dream",
      debut: 2014,
      hometown: "Washington, DC",
      height: 1.88,
      weight: 103,
      finisher: "The Purple RainMaker",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/velveteen_dream.png",
      imgFull: "assets/img/superstars_full/velveteen_dream.png",
      logo: "assets/img/logo/velveteen_dream.png",
      music: "pONMVifEz5U"
    },
    {
      name: "Samoa Joe",
      debut: 1999,
      hometown: "La Isla de Samoa",
      height: 1.88,
      weight: 130,
      finisher: "Coquina Clutch",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/samoa_joe.png",
      imgFull: "assets/img/superstars_full/samoa_joe.png",
      logo: "assets/img/logo/samoa_joe.png",
      music: "z--BViySvdQ"
    },
    {
      name: "The Miz",
      debut: 2003,
      hometown: "Cleveland, Ohio",
      height: 1.88,
      weight: 100,
      finisher: "Skull-Crushing Finale",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/the_miz.png",
      imgFull: "assets/img/superstars_full/the_miz.png",
      logo: "assets/img/logo/the_miz.png",
      music: "-hRrt6X-s0I"
    },
    {
      name: "Matt Riddle",
      debut: 2015,
      hometown: "Las Vegas, Nevada",
      height: 1.88,
      weight: 98,
      finisher: "Bromission / The Final Flash",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/matt_riddle.png",
      imgFull: "assets/img/superstars_full/matt_riddle.png",
      logo: "assets/img/logo/matt_riddle.png",
      music: "zn0Kduo5E1A"
    },
    {
      name: "Ricochet",
      debut: 2004,
      hometown: "Paducah, Kentucky",
      height: 1.78,
      weight: 74,
      finisher: "630 Splash",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/ricochet.png",
      imgFull: "assets/img/superstars_full/ricochet.png",
      logo: "assets/img/logo/ricochet.png",
      music: "12RhOL-zGjM"
    },
    {
      name: "Sami Zayn",
      debut: 2002,
      hometown: "Montreal, Quebec, Canadá",
      height: 1.85,
      weight: 93,
      finisher: "Helluva Kick",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/sami_zayn.png",
      imgFull: "assets/img/superstars_full/sami_zayn.png",
      logo: "assets/img/logo/sami_zayn.png",
      music: "4oGcuCablkU"
    },
    {
      name: "Lio Rush",
      debut: 2014,
      hometown: "Washington, D.C.",
      height: 1.67,
      weight: 73,
      finisher: "Rush Hour",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/lio_rush.png",
      imgFull: "assets/img/superstars_full/lio_rush.png",
      music: "FdhVqESuCxc"
    },
    {
      name: "Jack Gallagher",
      debut: 2006,
      hometown: "Manchester, Inglaterra",
      height: 1.73,
      weight: 76,
      finisher: "Running Dropkick",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/jack_gallagher.png",
      imgFull: "assets/img/superstars_full/jack_gallagher.png",
      music: "iTFx43OYBUc"
    },
    {
      name: "Oney Lorcan",
      debut: 2008,
      hometown: "Boston, Massachusetts",
      height: 1.83,
      weight: 91,
      finisher: "Half and half suplex",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/oney_lorcan.png",
      imgFull: "assets/img/superstars_full/oney_lorcan.png",
      music: "hVdIFb-3l-Y"
    },
    {
      name: "Danny Burch",
      debut: 2003,
      hometown: "Londres, Inglaterra",
      height: 1.83,
      weight: 109,
      finisher: "The London Bridge",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/danny_burch.png",
      imgFull: "assets/img/superstars_full/danny_burch.png",
      music: "hVdIFb-3l-Y"
    },
    {
      name: "Drew Gulak",
      debut: 2005,
      hometown: "University City, Filadelfia, Pensilvania",
      height: 1.83,
      weight: 92,
      finisher: "Gulock",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/drew_gulak.png",
      imgFull: "assets/img/superstars_full/drew_gulak.png",
      music: "iRETLzTPzOc"
    },
    {
      name: "Trent Seven",
      debut: 2009,
      hometown: "Wolverhampton, Inglaterra",
      height: 1.80,
      weight: 98,
      finisher: "Seven Stars Lariat",
      show: this._showService.getShow("3"),
      faction: "Moustache Mountain",
      img: "assets/img/superstars/trent_seven.png",
      imgFull: "assets/img/superstars_full/trent_seven.png",
      logo: "assets/img/logo/moustache_mountain.png",
      music: "Ql_Z5_EbtUo"
    },
    {
      name: "Toni Storm",
      debut: 2009,
      hometown: "Gold Coast, Queensland, Australia",
      height: 1.65,
      weight: 65,
      finisher: "Storm Zero",
      show: this._showService.getShow("3"),
      img: "assets/img/superstars/toni_storm.png",
      imgFull: "assets/img/superstars_full/toni_storm.png",
      logo: "assets/img/logo/toni_storm.png",
      music: "6NJJcqe6_SY"
    },
    {
      name: "Paige",
      debut: 2005,
      hometown: "Norwich, Inglaterra",
      height: 1.73,
      weight: 54,
      finisher: "Paige-Turner",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/paige.png",
      imgFull: "assets/img/superstars_full/paige.png",
      logo: "assets/img/logo/paige.png",
      music: "hvgpRvObDZQ"
    },
    {
      name: "John Cena",
      debut: 1999,
      hometown: "West Newbury, Massachusetts",
      height: 1.91,
      weight: 118,
      finisher: "Attitude Adjustment",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/john_cena.png",
      imgFull: "assets/img/superstars_full/john_cena.png",
      logo: "assets/img/logo/john_cena.png",
      music: "-cZ7ndjhhps"
    },
    {
      name: "Sheamus",
      debut: 2002,
      hometown: "Dublin, Irlanda",
      height: 1.98,
      weight: 121,
      finisher: "Brogue Kick",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/sheamus.png",
      imgFull: "assets/img/superstars_full/sheamus.png",
      logo: "assets/img/logo/sheamus.png",
      music: "uGUnicmmD-Q"
    },
    {
      name: "Big Show",
      debut: 1995,
      hometown: "Tampa, Florida",
      height: 2.13,
      weight: 180,
      finisher: "Chokeslam / KO Punch",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/big_show.png",
      imgFull: "assets/img/superstars_full/big_show.png",
      logo: "assets/img/logo/big_show.png",
      music: "eN40w31UFqY"
    },
    {
      name: "Andre the Giant",
      debut: 1964,
      hometown: "Grenoble, Francia",
      height: 2.24,
      weight: 236,
      finisher: "Sitdown Splash",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/andre_the_giant.png",
      imgFull: "assets/img/superstars_full/andre_the_giant.png",
      logo: "assets/img/logo/andre_the_giant.jpg",
      music: "S59nQIveUZw"
    },
    {
      name: "Eddie Guerrero",
      debut: 1987,
      hometown: "El Paso, Texas",
      height: 1.73,
      weight: 103,
      finisher: "Frog Splash / Lasso from El Paso",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/eddie_guerrero.png",
      imgFull: "assets/img/superstars_full/eddie_guerrero.png",
      logo: "assets/img/logo/eddie_guerrero.jpg",
      music: "oUb_UsSJtGk"
    },
    {
      name: "Ariya Daivari",
      debut: 2006,
      hometown: "Minneapolis, Minnesota",
      height: 1.78,
      weight: 86,
      finisher: "Frog Splash",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/ariya_daivari.png",
      imgFull: "assets/img/superstars_full/ariya_daivari.png",
      music: "bxae1NwvxbU"
    },
    {
      name: "Batista",
      debut: 1997,
      hometown: "Washington, D.C.",
      height: 1.98,
      weight: 126,
      finisher: "Batista Bomb",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/batista.png",
      imgFull: "assets/img/superstars_full/batista.png",
      logo: "assets/img/logo/batista.png",
      music: "7JpdptTqny8"
    },
    {
      name: "Ronda Rousey",
      debut: 2018,
      hometown: "Riverside County, California",
      height: 1.70,
      weight: 61,
      finisher: "Armbar",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/ronda_rousey.png",
      imgFull: "assets/img/superstars_full/ronda_rousey.png",
      logo: "assets/img/logo/ronda_rousey.png",
      music: "XrnnY32kV_I"
    },
    {
      name: "Keith Lee",
      debut: 2005,
      hometown: "Wichita Falls, Texas",
      height: 1.88,
      weight: 154,
      finisher: "Spirit Bomb",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/keith_lee.png",
      imgFull: "assets/img/superstars_full/keith_lee.png",
      music: "TANW61P7ZUg"
    },
    {
      name: "Kay Lee Ray",
      debut: 2009,
      hometown: "Glasgow, Escocia",
      height: 1.73,
      weight: 51,
      finisher: "Shotgun Stunner",
      show: this._showService.getShow("3"),
      img: "assets/img/superstars/kay_lee_ray.png",
      imgFull: "assets/img/superstars_full/kay_lee_ray.png",
      music: "ISbFQTV_mWg"
    },
    {
      name: "Ilja Dragunov",
      debut: 2012,
      hometown: "Moscú, Rusia",
      height: 1.75,
      weight: 85,
      finisher: "Grüße aus Moskau",
      show: this._showService.getShow("3"),
      img: "assets/img/superstars/ilja_dragunov.png",
      imgFull: "assets/img/superstars_full/ilja_dragunov.png",
      music: "MRu3Xa76W70"
    },
    {
      name: "Mark Coffey",
      debut: 2010,
      hometown: "Glasgow, Escocia",
      height: 1.88,
      weight: 108,
      finisher: "Crowning Glory",
      show: this._showService.getShow("3"),
      faction: "Gallus",
      img: "assets/img/superstars/mark_coffey.png",
      imgFull: "assets/img/superstars_full/mark_coffey.png",
      music: "vCLW9IKyJ-Q"
    },
    {
      name: "Wolfgang",
      debut: 2003,
      hometown: "Glasgow, Escocia",
      height: 1.85,
      weight: 116,
      finisher: "Damage Point",
      show: this._showService.getShow("3"),
      faction: "Gallus",
      img: "assets/img/superstars/wolfgang.png",
      imgFull: "assets/img/superstars_full/wolfgang.png",
      music: "vCLW9IKyJ-Q"
    },
    {
      name: "Bobby Lashley",
      debut: 2003,
      hometown: "Colorado Springs, Colorado",
      height: 1.88,
      weight: 126,
      finisher: "Dominator",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/bobby_lashley.png",
      imgFull: "assets/img/superstars_full/bobby_lashley.png",
      music: "se9jR594lVI"
    },
    {
      name: "Akam",
      debut: 2015,
      hometown: "Abbotsford, Columbia Británica, Canadá",
      height: 1.88,
      weight: 123,
      finisher: "Last Chapter",
      show: this._showService.getShow("0"),
      faction: "The Authors of Pain",
      img: "assets/img/superstars/akam.png",
      imgFull: "assets/img/superstars_full/akam.png",
      logo: "assets/img/logo/aop.png",
      music: "lNpW0T4ALYw"
    },
    {
      name: "Rezar",
      debut: 2016,
      hometown: "Albania",
      height: 1.93,
      weight: 140,
      finisher: "Last Chapter",
      show: this._showService.getShow("0"),
      faction: "The Authors of Pain",
      img: "assets/img/superstars/rezar.png",
      imgFull: "assets/img/superstars_full/rezar.png",
      logo: "assets/img/logo/aop.png",
      music: "lNpW0T4ALYw"
    },
    {
      name: "Cesaro",
      debut: 2000,
      hometown: "Lucerne, Suiza",
      height: 1.96,
      weight: 105,
      finisher: "Neutralizer",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/cesaro.png",
      imgFull: "assets/img/superstars_full/cesaro.png",
      music: "wqoZJ5eJIZs"
    },
    {
      name: "Rhea Ripley",
      debut: 2013,
      hometown: "Adelaide, Australia",
      height: 1.73,
      weight: 62,
      finisher: "Riptide",
      show: this._showService.getShow("3"),
      img: "assets/img/superstars/rhea_ripley.png",
      imgFull: "assets/img/superstars_full/rhea_ripley.png",
      music: "QNyfrQ8rAOM"
    },
    {
      name: "Ethan Carter III",
      debut: 2002,
      hometown: "Cleveland, Ohio",
      height: 1.88,
      weight: 109,
      finisher: "ECD – Ethan Carter's Driver",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/ec3.png",
      imgFull: "assets/img/superstars_full/ec3.png",
      music: "aTs4mb_CBos"
    },
    {
      name: "CM Punk",
      debut: 1999,
      hometown: "Chicago, Illinois",
      height: 1.88,
      weight: 99,
      finisher: "GTS – Go To Sleep",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/cm_punk.png",
      imgFull: "assets/img/superstars_full/cm_punk.png",
      logo: "assets/img/logo/cm_punk.png",
      music: "fFqxDrmQLnQ"
    },
    {
      name: "Tye Dillinger",
      nickname: "The Perfect 10",
      debut: 2001,
      hometown: "Niagara Falls, Ontario",
      height: 1.91,
      weight: 107,
      finisher: "Tye Breaker",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/tye_dillinger.png",
      imgFull: "assets/img/superstars_full/tye_dillinger.png",
      logo: "assets/img/logo/tye_dillinger.png",
      music: "raDk1uBVSRc"
    },
    {
      name: "The Gobbledy Gooker",
      debut: 1973,
      hometown: "El Paso, Texas",
      height: 1.78,
      weight: 103,
      finisher: "Butterfly Suplex",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/gobbledy_gooker.png",
      imgFull: "assets/img/superstars_full/gobbledy_gooker.png",
      music: "1QQs2IODODA"
    },
    {
      name: "Brian Kendrick",
      debut: 1999,
      hometown: "Venice, California",
      height: 1.73,
      weight: 83,
      finisher: "Captain's Hook",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/brian_kendrick.png",
      imgFull: "assets/img/superstars_full/brian_kendrick.png",
      music: "pyiW4_1hwkM"
    },
    {
      name: "Jordan Devlin",
      debut: 2006,
      hometown: "Bray, Co. Wicklow, Irlanda",
      height: 1.78,
      weight: 82,
      finisher: "Ireland's Call",
      show: this._showService.getShow("3"),
      img: "assets/img/superstars/jordan_devlin.png",
      imgFull: "assets/img/superstars_full/jordan_devlin.png",
      music: "_cipSRIBMxc"
    },
    {
      name: "Baron Corbin",
      nickname: "King",
      debut: 2012,
      hometown: "Kansas City",
      height: 2.03,
      weight: 129,
      finisher: "End of Days",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/king_corbin.png",
      imgFull: "assets/img/superstars_full/king_corbin.png",
      logo: "assets/img/logo/baron_corbin.png",
      music: "tqWlBxd-GIQ"
    },
    {
      name: "Tucker Knight",
      debut: 2015,
      hometown: "Hubbard, Oregon",
      height: 1.88,
      weight: 128,
      finisher: "Compactor",
      show: this._showService.getShow("1"),
      faction: "Heavy Machinery",
      img: "assets/img/superstars/tucker_knight.png",
      imgFull: "assets/img/superstars_full/tucker_knight.png",
      logo: "assets/img/logo/heavy_machinery.jpg",
      music: "eAgL5vQ7ty4"
    },
    {
      name: "Otis Dozovic",
      debut: 2015,
      hometown: "Pueblo, Colorado",
      height: 1.78,
      weight: 141,
      finisher: "Compactor",
      show: this._showService.getShow("1"),
      faction: "Heavy Machinery",
      img: "assets/img/superstars/otis_dozovic.png",
      imgFull: "assets/img/superstars_full/otis_dozovic.png",
      logo: "assets/img/logo/heavy_machinery.jpg",
      music: "eAgL5vQ7ty4"
    },
    {
      name: "Killian Dain",
      debut: 2005,
      hometown: "Belfast, Irlanda del Norte",
      height: 1.93,
      weight: 146,
      finisher: "Ulster Plantation",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/killian_dain.png",
      imgFull: "assets/img/superstars_full/killian_dain.png",
      music: "ZkHk90t6t20"
    },
    {
      name: "Nikki Cross",
      debut: 2008,
      hometown: "Glasgow, Escocia",
      height: 1.55,
      weight: 55,
      finisher: "The Purge",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/nikki_cross.png",
      imgFull: "assets/img/superstars_full/nikki_cross.png",
      music: "gTsTcc80rHo"
    },
    {
      name: "Nia Jax",
      debut: 2015,
      hometown: "San Diego, California",
      height: 1.83,
      weight: 123,
      finisher: "Legdrop / Samoan Drop",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/nia_jax.png",
      imgFull: "assets/img/superstars_full/nia_jax.png",
      music: "-UuG9QlwbuI"
    },
    {
      name: "Montez Ford",
      debut: 2015,
      hometown: "Chicago, Illinois",
      height: 1.85,
      weight: 105,
      finisher: "Frog Splash",
      show: this._showService.getShow("0"),
      faction: "Street Profits",
      img: "assets/img/superstars/montez_ford.png",
      imgFull: "assets/img/superstars_full/montez_ford.png",
      music: "Nngn8SdCxWI"
    },
    {
      name: "Angelo Dawkins",
      debut: 2012,
      hometown: "Cincinnati, Ohio",
      height: 1.95,
      weight: 118,
      finisher: "Sitdown Powerbomb",
      show: this._showService.getShow("0"),
      faction: "Street Profits",
      img: "assets/img/superstars/angelo_dawkins.png",
      imgFull: "assets/img/superstars_full/angelo_dawkins.png",
      music: "Nngn8SdCxWI"
    },
    {
      name: "Akira Tozawa",
      debut: 2005,
      hometown: "Kobe, Japón",
      height: 1.70,
      weight: 71,
      finisher: "Top-rope Senton",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/akira_tozawa.png",
      imgFull: "assets/img/superstars_full/akira_tozawa.png",
      music: "i4ygQO_yLJI"
    },
    {
      name: "Jinder Mahal",
      debut: 2003,
      hometown: "Punjab, India",
      height: 1.96,
      weight: 108,
      finisher: "Khallas",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/jinder_mahal.png",
      imgFull: "assets/img/superstars_full/jinder_mahal.png",
      logo: "assets/img/logo/jinder_mahal.png",
      music: "hCC0O6JyhQU"
    },
    {
      name: "Kane",
      debut: 1992,
      hometown: "Knoxville, Tennessee",
      height: 2.13,
      weight: 147,
      finisher: "Chokeslam / Tombstone",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/kane.png",
      imgFull: "assets/img/superstars_full/kane.png",
      music: "WZZGrtWIAJc"
    },
    {
      name: "Steve Austin",
      nickname: "Stone Cold",
      debut: 1989,
      hometown: "Victoria, Texas",
      height: 1.88,
      weight: 114,
      finisher: "Stone Cold Stunner",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/steve_austin.png",
      imgFull: "assets/img/superstars_full/steve_austin.png",
      logo: "assets/img/logo/steve_austin.png",
      music: "MrJLsNo9sCU"
    },
    {
      name: "Shawn Michaels",
      nickname: "HBK",
      debut: 1988,
      hometown: "San Antonio, Texas",
      height: 1.85,
      weight: 102,
      finisher: "Sweet Chin Music",
      show: this._showService.getShow("5"),
      faction: "D-Generation X",
      img: "assets/img/superstars/shawn_michaels.png",
      imgFull: "assets/img/superstars_full/shawn_michaels.png",
      logo: "assets/img/logo/dx.png",
      music: "XEA1nwJNT9E"
    },
    {
      name: "Triple H",
      debut: 1992,
      hometown: "Greenwich, Connecticut",
      height: 1.93,
      weight: 116,
      finisher: "Pedigree",
      show: this._showService.getShow("5"),
      faction: "D-Generation X",
      img: "assets/img/superstars/triple_h.png",
      imgFull: "assets/img/superstars_full/triple_h.png",
      logo: "assets/img/logo/dx.png",
      music: "uWcG4mCp0Zw"
    },
    {
      name: "Randy Savage",
      nickname: "Macho Man",
      debut: 1973,
      hometown: "Sarasota, Florida",
      height: 1.85,
      weight: 102,
      finisher: "Diving elbow drop",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/randy_savage.png",
      imgFull: "assets/img/superstars_full/randy_savage.png",
      music: "Rblh_0d7Qlw"
    },
    {
      name: "Mick Foley",
      debut: 1983,
      hometown: "Long Island, Nueva York",
      height: 1.88,
      weight: 130,
      finisher: "Mandible Claw",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/mick_foley.png",
      imgFull: "assets/img/superstars_full/mick_foley.png",
      logo: "assets/img/logo/mick_foley.png",
      music: "wiftmVaf0eA"
    },
    {
      name: "Edge",
      debut: 1992,
      hometown: "Toronto, Ontario, Canadá",
      height: 1.96,
      weight: 109,
      finisher: "Spear",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/edge.png",
      imgFull: "assets/img/superstars_full/edge.png",
      logo: "assets/img/logo/edge.png",
      music: "--5tBLiE1Fk"
    },
    {
      name: "Hulk Hogan",
      debut: 1977,
      hometown: "Venice Beach, California",
      height: 2.03,
      weight: 137,
      finisher: "Leg drop",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/hulk_hogan.png",
      imgFull: "assets/img/superstars_full/hulk_hogan.png",
      music: "9lZDgGr1PO0"
    },
    {
      name: "Goldberg",
      debut: 1997,
      hometown: "Venice Beach, California",
      height: 1.93,
      weight: 129,
      finisher: "Jackhammer",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/goldberg.png",
      imgFull: "assets/img/superstars_full/goldberg.png",
      logo: "assets/img/logo/goldberg.png",
      music: "qvnXksCRzBI"
    },
    {
      name: "Big Boss Man",
      debut: 1985,
      hometown: "Cobb County, Georgia",
      height: 1.98,
      weight: 149,
      finisher: "Boss Man Slam",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/big_boss_man.png",
      imgFull: "assets/img/superstars_full/big_boss_man.png",
      music: "ioZTE_S4xDU"
    },
    {
      name: "Bret Hart",
      debut: 1976,
      hometown: "Calgary, Alberta, Canadá",
      height: 1.85,
      weight: 106,
      finisher: "The Sharpshooter",
      show: this._showService.getShow("5"),
      faction: "The Hart Foundation",
      img: "assets/img/superstars/bret_hart.png",
      imgFull: "assets/img/superstars_full/bret_hart.png",
      logo: "assets/img/logo/bret_hart.png",
      music: "OJnl8bk1Zgk"
    },
    {
      name: "Jim Neidhart",
      nickname: "The Anvil",
      debut: 1979,
      hometown: "Reno, Nevada",
      height: 1.80,
      weight: 127,
      finisher: "Anvil Flattener",
      show: this._showService.getShow("5"),
      faction: "The Hart Foundation",
      img: "assets/img/superstars/jim_neidhart.png",
      imgFull: "assets/img/superstars_full/jim_neidhart.png",
      music: "8jAJIuAdsLw"
    },
    {
      name: "Rikishi",
      debut: 1985,
      hometown: "La Isla de Samoa",
      height: 1.85,
      weight: 193,
      finisher: "The Stink Face",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/rikishi.png",
      imgFull: "assets/img/superstars_full/rikishi.png",
      music: "VviAb9Q_7Lg"
    },
    {
      name: "Ric Flair",
      debut: 1972,
      hometown: "Charlotte, Carolina del Norte",
      height: 1.80,
      weight: 110,
      finisher: "Figure-Four Leglock",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/ric_flair.png",
      imgFull: "assets/img/superstars_full/ric_flair.png",
      music: "IyVvGBMrHQk"
    },
    {
      name: "Kurt Angle",
      debut: 1998,
      hometown: "Pittsburgh, Pensilvania",
      height: 1.83,
      weight: 109,
      finisher: "Angle Slam / Ankle Lock",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/kurt_angle.png",
      imgFull: "assets/img/superstars_full/kurt_angle.png",
      music: "h0GY_l5D9mA"
    },
    {
      name: "Chris Jericho",
      debut: 1990,
      hometown: "Winnipeg, Manitoba, Canadá",
      height: 1.83,
      weight: 102,
      finisher: "Codebreaker / Walls of Jericho",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/chris_jericho.png",
      imgFull: "assets/img/superstars_full/chris_jericho.png",
      logo: "assets/img/logo/chris_jericho.jpg",
      music: "8PZCB0M1gJo"
    },
    {
      name: "Dwayne Johnson",
      nickname: "The Rock",
      debut: 1995,
      hometown: "Miami, Florida",
      height: 1.94,
      weight: 125,
      finisher: "Rock Bottom / The People's Elbow",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/the_rock.png",
      imgFull: "assets/img/superstars_full/the_rock.png",
      logo: "assets/img/logo/the_rock.png",
      music: "ZcIYOgcCcnM"
    },
    {
      name: "The Undertaker",
      debut: 1984,
      hometown: "Death Valley",
      height: 2.08,
      weight: 136,
      finisher: "Tombstone piledriver",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/undertaker.png",
      imgFull: "assets/img/superstars_full/undertaker.png",
      logo: "assets/img/logo/undertaker.png",
      music: "BYFH0BJ1ZDI"
    },
    {
      name: "The Honky Tonk Man",
      debut: 1977,
      hometown: "Memphis, Tennessee",
      height: 1.85,
      weight: 112,
      finisher: "Shake, Rattle and Roll",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/honky_tonk_man.png",
      imgFull: "assets/img/superstars_full/honky_tonk_man.png",
      music: "d0_XF_uQxRY"
    },
    {
      name: "Io Shirai",
      debut: 2007,
      hometown: "Tokyo, Japón",
      height: 1.56,
      weight: 55,
      finisher: "Moonsault",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/io_shirai.png",
      imgFull: "assets/img/superstars_full/io_shirai.png",
      music: "45YRSZH76_o"
    },
    {
      name: "Sting",
      debut: 1985,
      hometown: "Venice Beach, California",
      height: 1.88,
      weight: 114,
      finisher: "Scorpion Deathlock",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/sting.png",
      imgFull: "assets/img/superstars_full/sting.png",
      music: "Z_dQKo_EV0c"
    },
    {
      name: "Tony Nese",
      debut: 2001,
      hometown: "Long Island, Nueva York",
      height: 1.75,
      weight: 90,
      finisher: "Running Nese",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/tony_nese.png",
      imgFull: "assets/img/superstars_full/tony_nese.png",
      music: "-oZLbp00Rpo"
    },
    {
      name: "Billie Kay",
      debut: 2007,
      hometown: "Sydney, Australia",
      height: 1.73,
      weight: 60,
      finisher: "Shades of Kay",
      show: this._showService.getShow("0"),
      faction: "The IIconics",
      img: "assets/img/superstars/billie_kay.png",
      imgFull: "assets/img/superstars_full/billie_kay.png",
      music: "gopWUYaahaM"
    },
    {
      name: "Peyton Royce",
      debut: 2009,
      hometown: "Sydney, Australia",
      height: 1.70,
      weight: 60,
      finisher: "Peyton-Plex",
      show: this._showService.getShow("0"),
      faction: "The IIconics",
      img: "assets/img/superstars/peyton_royce.png",
      imgFull: "assets/img/superstars_full/peyton_royce.png",
      music: "gopWUYaahaM"
    },
    {
      name: "Rey Mysterio",
      debut: 1989,
      hometown: "San Diego, California",
      height: 1.60,
      weight: 70,
      finisher: "619",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/rey_mysterio.png",
      imgFull: "assets/img/superstars_full/rey_mysterio.png",
      music: "jvFfIVlRzlw"
    },
    {
      name: "Rusev",
      debut: 2008,
      hometown: "Bulgaria",
      height: 1.83,
      weight: 138,
      finisher: "The Accolade",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/rusev.png",
      imgFull: "assets/img/superstars_full/rusev.png",
      music: "kWw5ODHwpdU"
    },
    {
      name: "Shane McMahon",
      debut: 1990,
      hometown: "Greenwich, Connecticut",
      height: 1.88,
      weight: 106,
      finisher: "Coast to Coast",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/shane_mcmahon.png",
      imgFull: "assets/img/superstars_full/shane_mcmahon.png",
      music: "tbXM5HxP4Lg"
    },
    {
      name: "Ted DiBiase",
      nickname: "Million Dollar Man",
      debut: 1974,
      hometown: "Palm Beach, Florida",
      height: 1.91,
      weight: 120,
      finisher: "The Million Dollar Dream",
      show: this._showService.getShow("5"),
      img: "assets/img/superstars/ted_dibiase.png",
      imgFull: "assets/img/superstars_full/ted_dibiase.png",
      music: "XFTmPzMbvBU"
    },
    {
      name: "Alexander Wolfe",
      debut: 2004,
      hometown: "Dresden, Sachsen",
      height: 1.85,
      weight: 111,
      finisher: "Cave Canem",
      show: this._showService.getShow("3"),
      faction: "Imperium",
      img: "assets/img/superstars/alexander_wolfe.png",
      imgFull: "assets/img/superstars_full/alexander_wolfe.png",
      music: "XuvSKH-OCY0"
    },
    {
      name: "Fabian Aichner",
      debut: 2011,
      hometown: "South Tyrol, Italia",
      height: 1.83,
      weight: 100,
      finisher: "Hasta La Vista",
      show: this._showService.getShow("3"),
      faction: "Imperium",
      img: "assets/img/superstars/fabian_aichner.png",
      imgFull: "assets/img/superstars_full/fabian_aichner.png",
      music: "XuvSKH-OCY0"
    },
    {
      name: "Marcel Barthel",
      debut: 2008,
      hometown: "Hamburg, Alemania",
      height: 1.91,
      weight: 100,
      finisher: "Landungsbrücken",
      show: this._showService.getShow("3"),
      faction: "Imperium",
      img: "assets/img/superstars/marcel_barthel.png",
      imgFull: "assets/img/superstars_full/marcel_barthel.png",
      music: "XuvSKH-OCY0"
    },
    {
      name: "Fandango",
      debut: 1999,
      hometown: "Boston, Massachusetts",
      height: 1.91,
      weight: 111,
      finisher: "Last Dance",
      show: this._showService.getShow("2"),
      faction: "Breezango",
      img: "assets/img/superstars/fandango.png",
      imgFull: "assets/img/superstars_full/fandango.png",
      music: "lainloKTx4c"
    },
    {
      name: "Tyler Breeze",
      debut: 2007,
      hometown: "Penticton, Columbia Británica, Canadá",
      height: 1.85,
      weight: 88,
      finisher: "Beauty Shot / Supermodel Kick",
      show: this._showService.getShow("2"),
      faction: "Breezango",
      img: "assets/img/superstars/tyler_breeze.png",
      imgFull: "assets/img/superstars_full/tyler_breeze.png",
      music: "lainloKTx4c"
    },
    {
      name: "Dolph Ziggler",
      debut: 2004,
      hometown: "Hollywood, Florida",
      height: 1.83,
      weight: 97,
      finisher: "Zig Zag",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/dolph_ziggler.png",
      imgFull: "assets/img/superstars_full/dolph_ziggler.png",
      music: "bp0j9KGjRCE"
    },
    {
      name: "Dean Ambrose",
      debut: 2004,
      hometown: "Cincinnati, Ohio",
      height: 1.88,
      weight: 102,
      finisher: "Dirty Deeds",
      show: this._showService.getShow("5"),
      faction: "The Shield",
      img: "assets/img/superstars/dean_ambrose.png",
      imgFull: "assets/img/superstars_full/dean_ambrose.png",
      logo: "assets/img/logo/dean_ambrose.png",
      music: "rTjDkDtYeEU"
    },
    {
      name: "Zack Ryder",
      debut: 2004,
      hometown: "Long Island, Nueva York",
      height: 1.88,
      weight: 102,
      finisher: "Rough Ryder",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/zack_ryder.png",
      imgFull: "assets/img/superstars_full/zack_ryder.png",
      music: "rrusb3JWUWY"
    },
    {
      name: "Apollo Crews",
      debut: 2009,
      hometown: "Sacramento, California",
      height: 1.85,
      weight: 118,
      finisher: "The Chariot",
      show: this._showService.getShow("1"),
      faction: "Titus Worldwide",
      img: "assets/img/superstars/apollo_crews.png",
      imgFull: "assets/img/superstars_full/apollo_crews.png",
      music: "XkGbuIySDto"
    },
    {
      name: "Titus O'Neil",
      debut: 2009,
      hometown: "Live Oak, Florida",
      height: 1.98,
      weight: 120,
      finisher: "Clash of the Titus",
      show: this._showService.getShow("0"),
      faction: "Titus Worldwide",
      img: "assets/img/superstars/titus_oneil.png",
      imgFull: "assets/img/superstars_full/titus_oneil.png",
      music: "xopFLztWr2U"
    },
    {
      name: "Bianca Belair",
      debut: 2016,
      hometown: "Knoxville, Tennessee",
      height: 1.70,
      weight: 57,
      finisher: "K.O.D.",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/bianca_belair.png",
      imgFull: "assets/img/superstars_full/bianca_belair.png",
      music: "raYuMzqfqcA"
    },
    {
      name: "Dash Wilder",
      debut: 2005,
      hometown: "Raleigh, Carolina del Norte",
      height: 1.78,
      weight: 101,
      finisher: "Shatter Machine",
      show: this._showService.getShow("1"),
      faction: "The Revival",
      img: "assets/img/superstars/dash_wilder.png",
      imgFull: "assets/img/superstars_full/dash_wilder.png",
      music: "-BW1UQPkBik"
    },
    {
      name: "Scott Dawson",
      debut: 2004,
      hometown: "Whiteville, Carolina del Norte",
      height: 1.80,
      weight: 106,
      finisher: "Shatter Machine",
      show: this._showService.getShow("1"),
      faction: "The Revival",
      img: "assets/img/superstars/scott_dawson.png",
      imgFull: "assets/img/superstars_full/scott_dawson.png",
      music: "-BW1UQPkBik"
    },
    {
      name: "Ruby Riott",
      debut: 2010,
      hometown: "Lafayette, Indiana",
      height: 1.75,
      weight: 60,
      finisher: "Riott Kick",
      show: this._showService.getShow("0"),
      faction: "The Riott Squad",
      img: "assets/img/superstars/ruby_riott.png",
      imgFull: "assets/img/superstars_full/ruby_riott.png",
      music: "NNCUjay0gbE"
    },
    {
      name: "Sarah Logan",
      debut: 2011,
      hometown: "Louisville, Kentucky",
      height: 1.65,
      weight: 63,
      finisher: "Kentucky Knee",
      show: this._showService.getShow("0"),
      faction: "The Riott Squad",
      img: "assets/img/superstars/sarah_logan.png",
      imgFull: "assets/img/superstars_full/sarah_logan.png",
      music: "NNCUjay0gbE"
    },
    {
      name: "Liv Morgan",
      debut: 2015,
      hometown: "Elmwood Park, Nueva Jersey",
      height: 1.63,
      weight: 57,
      finisher: "Jersey Codebreaker",
      show: this._showService.getShow("0"),
      faction: "The Riott Squad",
      img: "assets/img/superstars/liv_morgan.png",
      imgFull: "assets/img/superstars_full/liv_morgan.png",
      music: "NNCUjay0gbE"
    },
    {
      name: "Lacey Evans",
      debut: 2014,
      hometown: "Lady's Island, Beaufort, Carolina del Sur",
      height: 1.73,
      weight: 59,
      finisher: "Woman's Right",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/lacey_evans.png",
      imgFull: "assets/img/superstars_full/lacey_evans.png",
      music: "vjlc-aFz28U"
    },
    {
      name: "Luke Harper",
      debut: 2003,
      hometown: "Lincoln, Nebraska",
      height: 1.96,
      weight: 119,
      finisher: "Discus clothesline",
      show: this._showService.getShow("1"),
      faction: "The Bludgeon Brothers",
      img: "assets/img/superstars/luke_harper.png",
      imgFull: "assets/img/superstars_full/luke_harper.png",
      music: "ejLbTnodkuI"
    },
    {
      name: "Erick Rowan",
      debut: 2003,
      hometown: "Minneapolis, Minnesota",
      height: 2.03,
      weight: 143,
      finisher: "Iron Claw",
      show: this._showService.getShow("0"),
      faction: "The Bludgeon Brothers",
      img: "assets/img/superstars/erick_rowan.png",
      imgFull: "assets/img/superstars_full/erick_rowan.png",
      music: "ejLbTnodkuI"
    },
    {
      name: "Ember Moon",
      debut: 2007,
      hometown: "Dallas, Texas",
      height: 1.55,
      weight: 54,
      finisher: "Eclipse",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/ember_moon.png",
      imgFull: "assets/img/superstars_full/ember_moon.png",
      music: "uZ06x1fgz-Y"
    },
    {
      name: "Cedric Alexander",
      debut: 2009,
      hometown: "Charlotte, Carolina del Norte",
      height: 1.80,
      weight: 95,
      finisher: "Lumbar Check",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/cedric_alexander.png",
      imgFull: "assets/img/superstars_full/cedric_alexander.png",
      music: "fzCJo4lIhSM"
    },
    {
      name: "Damian Priest",
      debut: 2004,
      hometown: "Ciudad de Nueva York, Nueva York",
      height: 2.01,
      weight: 114,
      finisher: "Reckoning",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/damian_priest.png",
      imgFull: "assets/img/superstars_full/damian_priest.png",
      music: "Ofpb-hJDP0M"
    },
    {
      name: "Dominik Dijakovic",
      debut: 2012,
      hometown: "Tyngsboro, Massachusetts",
      height: 2.01,
      weight: 125,
      finisher: "Feast Your Eyes",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/dominik_dijakovic.png",
      imgFull: "assets/img/superstars_full/dominik_dijakovic.png",
      music: "SYrwDoqQGtQ"
    },
    {
      name: "Candice LeRae",
      debut: 2002,
      hometown: "Riverside, California",
      height: 1.57,
      weight: 51,
      finisher: "Quebrada",
      show: this._showService.getShow("2"),
      img: "assets/img/superstars/candice_lerae.png",
      imgFull: "assets/img/superstars_full/candice_lerae.png",
      logo: "assets/img/logo/candice_lerae.png",
      music: "hReGb_dzCuw"
    },
    {
      name: "Elias",
      debut: 2008,
      hometown: "Pittsburgh, Pensilvania",
      height: 1.83,
      weight: 99,
      finisher: "Drift Away",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/elias.png",
      imgFull: "assets/img/superstars_full/elias.png",
      logo: "assets/img/logo/elias.png",
      music: "WgIFJhPFgaU"
    },
    {
      name: "No Way Jose",
      debut: 2013,
      hometown: "Santo Domingo, República Dominicana",
      height: 1.91,
      weight: 111,
      finisher: "Fastball Punch",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/no_way_jose.png",
      imgFull: "assets/img/superstars_full/no_way_jose.png",
      music: "Vtrdr-nxvAA"
    },
    {
      name: "Carmella",
      debut: 2013,
      hometown: "Staten Island, Nueva York",
      height: 1.65,
      weight: 50,
      finisher: "Code of Silence",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/carmella.png",
      imgFull: "assets/img/superstars_full/carmella.png",
      music: "HIcb-j_IpmU"
    },
    {
      name: "Gran Metalik",
      debut: 2005,
      hometown: "Guadalajara, Jalisco, México",
      height: 1.76,
      weight: 79,
      finisher: "Metalik Driver",
      show: this._showService.getShow("4"),
      faction: "Lucha House Party",
      img: "assets/img/superstars/gran_metalik.png",
      imgFull: "assets/img/superstars_full/gran_metalik.png",
      music: "iv1dOB4P_nU"
    },
    {
      name: "Lince Dorado",
      debut: 2006,
      hometown: "San Juan, Puerto Rico",
      height: 1.70,
      weight: 76,
      finisher: "Cara Dorada",
      show: this._showService.getShow("4"),
      faction: "Lucha House Party",
      img: "assets/img/superstars/lince_dorado.png",
      imgFull: "assets/img/superstars_full/lince_dorado.png",
      music: "aGzPJoXBFWU"
    },
    {
      name: "Kalisto",
      debut: 2006,
      hometown: "Ciudad de México",
      height: 1.67,
      weight: 81,
      finisher: "Salida del Sol",
      show: this._showService.getShow("4"),
      faction: "Lucha House Party",
      img: "assets/img/superstars/kalisto.png",
      imgFull: "assets/img/superstars_full/kalisto.png",
      music: "c1Zf3ph5FXg"
    },
    {
      name: "Mojo Rawley",
      debut: 2012,
      hometown: "Alexandria, Virginia",
      height: 1.91,
      weight: 127,
      finisher: "Hyperdrive",
      show: this._showService.getShow("0"),
      img: "assets/img/superstars/mojo_rawley.png",
      imgFull: "assets/img/superstars_full/mojo_rawley.png",
      music: "e85gvZGVnD8"
    },
    {
      name: "Mustafa Ali",
      debut: 2003,
      hometown: "Chicago, Illinois",
      height: 1.78,
      weight: 82,
      finisher: "054",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/mustafa_ali.png",
      imgFull: "assets/img/superstars_full/mustafa_ali.png",
      music: "newJ_OhNaUk"
    },
    {
      name: "Noam Dar",
      debut: 2008,
      hometown: "Ayr, Escocia",
      height: 1.75,
      weight: 81,
      finisher: "Kneebar",
      show: this._showService.getShow("3"),
      img: "assets/img/superstars/noam_dar.png",
      imgFull: "assets/img/superstars_full/noam_dar.png",
      music: "2GnHj7RO39o"
    },
    {
      name: "Jimmy Uso",
      debut: 2007,
      hometown: "San Francisco, California",
      height: 1.88,
      weight: 109,
      finisher: "Double Uce",
      show: this._showService.getShow("0"),
      faction: "The Usos",
      img: "assets/img/superstars/jimmy_uso.png",
      imgFull: "assets/img/superstars_full/jimmy_uso.png",
      logo: "assets/img/logo/the_usos.png",
      music: "2QSTIdiIIbc"
    },
    {
      name: "Jey Uso",
      debut: 2007,
      hometown: "San Francisco, California",
      height: 1.85,
      weight: 103,
      finisher: "Double Uce",
      show: this._showService.getShow("0"),
      faction: "The Usos",
      img: "assets/img/superstars/jey_uso.png",
      imgFull: "assets/img/superstars_full/jey_uso.png",
      logo: "assets/img/logo/the_usos.png",
      music: "2QSTIdiIIbc"
    },
    {
      name: "Neville",
      debut: 2004,
      hometown: "Newcastle upon Tyne",
      height: 1.75,
      weight: 87,
      finisher: "Red Arrow / Rings of Saturn",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/neville.png",
      imgFull: "assets/img/superstars_full/neville.png",
      music: "EyAq4aLvoRs"
    },
    {
      name: "Heath Slater",
      debut: 2004,
      hometown: "Pineville, West Virginia",
      height: 1.88,
      weight: 97,
      finisher: "Smash Hit",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/heath_slater.png",
      imgFull: "assets/img/superstars_full/heath_slater.png",
      music: "D2S_5y_bfA0"
    },
    {
      name: "Rhyno",
      debut: 1995,
      hometown: "Detroit, Michigan",
      height: 1.78,
      weight: 134,
      finisher: "Gore",
      show: this._showService.getShow("1"),
      img: "assets/img/superstars/rhyno.png",
      imgFull: "assets/img/superstars_full/rhyno.png",
      music: "D3jzGODEI74"
    },
    {
      name: "TJP",
      debut: 1999,
      hometown: "Los Angeles, California",
      height: 1.78,
      weight: 81,
      finisher: "Kneebar",
      show: this._showService.getShow("4"),
      img: "assets/img/superstars/tjp.png",
      imgFull: "assets/img/superstars_full/tjp.png",
      music: "xGKmLM4LJEE"
    },
    {
      name: "Zack Gibson",
      debut: 2009,
      hometown: "Liverpool, Inglaterra",
      height: 1.91,
      weight: 82,
      finisher: "Shankly Gates",
      show: this._showService.getShow("3"),
      faction: "Grizzled Young Veterans",
      img: "assets/img/superstars/zack_gibson.png",
      imgFull: "assets/img/superstars_full/zack_gibson.png",
      music: "BZVzORkiAKc"
    },
    {
      name: "James Drake",
      debut: 2009,
      hometown: "Blackpool, Lancashire",
      height: 1.78,
      weight: 82,
      finisher: "Mr. Mayhem",
      show: this._showService.getShow("3"),
      faction: "Grizzled Young Veterans",
      img: "assets/img/superstars/james_drake.png",
      imgFull: "assets/img/superstars_full/james_drake.png",
      music: "Ge9-7bcAw-o"
    }
  ];

  constructor( private _showService: ShowService ) {}

  getSuperstars(){
    return this.superstars;
  }

  getSuperstar( index: string ){
    return this.superstars[index];
  }

  searchSuperstar( search: string, byFaction: boolean ): Superstar[]{
    let superstars: Superstar[] = [];
    search = search.toLowerCase();

    // This is required in order to show any result when a filter has been applied previously.
    this._showService.resetFilter();

    for (let i = 0; i < this.superstars.length; i++){
      if (byFaction){
        if (this.superstars[i].faction != undefined){
          let faction = this.superstars[i].faction.toLowerCase();
          if ( faction.indexOf(search) >= 0 ){
            superstars.push(this.superstars[i]);
          }
        }
      } else {
        let name = this.superstars[i].name.toLowerCase();
        let nickname = "";
        if (this.superstars[i].nickname != undefined){
          nickname = this.superstars[i].nickname.toLowerCase();
        }
        if ( name.indexOf(search) >= 0 || nickname.indexOf(search) >= 0){
          superstars.push(this.superstars[i]);
        }
      }
    }
    return superstars;
  }

  // Easter egg with superstar Bray Wyatt showing his in-ring persona.
  letHimIn(){
    console.log("Let me in");
    this.superstars[7].name = "The Fiend";
    this.superstars[7].finisher = "L̫E̥͍̟̤͈͇̱T͈̬̗ ͍͖̙͍͇M̙̞E͙ ͉̟͈͔͎͈IN̪͔͓͚̭"
    this.superstars[7].hometown = "Y̵̏̿̎͐͂ͤ͗̔ͮ̇̊ͫ̐̋҉̗̖̗̞̠̤̤͉̪̠̣̥̱̻͔Ȏͪ̽̍҉̢͎̘̺̝̝̹̳̩̮̺̙̝̖̱̯͘͝ͅͅW̧̹͚̝̪̬͈̝̘̖̖̰̲͊͑ͭͤͣ̐̄̐̑̌ͩ̕͢͞ͅI̷̢͙̹͔͔̝̣̬̗̜̦̯̲̤͔̬͈̩̱̊͛͊̈ͩͣͬ̎̉͌ͪ̔̽̎̚͝ͅE̵͖͎̝͙̽͑̓̇͟͠͝ ̛͉̜̺͙̩̪͉͚̻̯̖͇̩̺̘̑̂̚̕͢W̶̷̬͖͍̲̩͂̎ͬ͆̇͊̓͊͗͋̆̏̀̐̀̔̓̿́͢͡O̧̤̟͈͓͖̿̉͌̓ͥͣ͗̍̐͛͋ͥ̍ͨ̚͟͝͞ͅW̵̸̨̙̜̫̱͈͎͓̰̟͍͉̺̖ͪ͑̄͂̄̀ͬĬ̵̛̜̘̻̪͎̭̝̻͓̍ͦ̂͊̽͑ͩͨͭͥ̔́͘E̡̥̱͓̞̳̅̊ͣ̎́";
    this.superstars[7].img = "assets/img/superstars/bray_wyatt_2.png";
    this.superstars[7].imgFull = "assets/img/superstars_full/bray_wyatt_2.png";
    this.superstars[7].logo = "assets/img/logo/bray_wyatt.png";
    this.superstars[7].music = "eTR28PRBbDo";
  }

}

export interface Superstar {
  name: string;
  nickname: string;
  debut: number;
  hometown: string;
  height: number;
  weight: number;
  finisher: string;
  show: Show;
  faction: string;
  img: string;
  imgFull: string;
  logo: string;
  music: string;
}
